CREATE TABLE students (
    student_id integer generated by default as identity primary key,
    student_surname varchar(80) not null,
    student_name varchar(80), 
    student_age integer,
    student_group varchar(10) not null,
    student_year integer,
    constraint name_length check (char_length(student_name) between 2 and 40),
    constraint age_value check (student_age > 18),
    constraint study_years check (student_year > 0 and student_year < 5)
);

INSERT INTO students (student_surname, student_name, student_age, student_group, student_year)
VALUES
    ('Smith', 'John', 20, 'A', 2),
    ('Doe', 'Jane', 22, 'B', 3),
    ('Johnson', 'Michael', 21, 'A', 1),
    ('Williams', 'Emily', 19, 'C', 2),
    ('Brown', 'David', 23, 'B', 4),
    ('Johnson', 'Jane', 22, 'B', 3),
    ('Hills', 'Dave', 22, 'B', 3),
    ('Butcher', 'William', 22, 'B', 3),
    ('Matt', 'Jack', 22, 'B', 3),
    ('Matt', 'Ryan', 22, 'B', 3);


CREATE VIEW third_year_students as 
    SELECT student_surname, student_name, student_group FROM students where student_year = 3;

UPDATE third_year_students
    SET student_group = 'C';

DELETE FROM third_year_students
    WHERE student_surname = 'Doe' and student_name = 'Jane';

CREATE VIEW group_C as 
    SELECT student_surname, student_name FROM students where student_group = 'C';

UPDATE group_C
    SET student_year = student_year + 1;

create view age_22 as
    SELECT student_surname, student_name from students where age = 22;

UPDATE age_22
    set age = age + 1;

drop view age_22;
    
