CREATE TABLE journal (
    id integer generated by default as identity primary key,
    test_number integer,
    grade integer,
    subject varchar(80) not null,
    examination_date date not null
    constraint positive_test_number check (test_number > 0),
    constraint possible_grade check (grade between 0 and 5)
);

insert into journal (test_number, grade, subject, examination_date)
VALUES
    (12, 4, 'Math', '2000-12-12'),
    (41, 3, 'Physics', '2000-12-12'),
    (35, 5, 'Chemistry', '2000-12-12'),
    (19, 4, 'English', '2000-12-12'),
    (2, 1, 'French', '2000-12-12'),
    (9, 5, 'CS', '2000-12-12'),
    (15, 4, 'Biology', '2000-12-12');

BEGIN TRANSACTION;
UPDATE journal
    SET grade = 5;
select * from journal;
ROLLBACK;
select * from journal;

BEGIN TRANSACTION;
UPDATE journal
    SET grade = 3 where grade = 1;
savepoint update_journal;
    insert into journal(test_number, grade, subject, examination_date)
    values(17, 'German' '2000-12-12');
    rollbach to savepoint update_journal; 
    release savepoint update_journal;
    commit;
COMMIT;
